version: "3.2"
services:
  rancher:
    # replace username/repo:tag with your name and image details
    image: rancher/rancher
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"

