version: "3.2"
services:
  mayanedms-postgres:
    # replace username/repo:tag with your name and image details
    image: postgres:9.5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mayan
      - POSTGRES_DB=mayan
      - POSTGRES_PASSWORD=password
    networks:
      - net
    volumes:
      - type: bind
        source: /mnt/docker/mayan-edms/postgres
        target: /var/lib/postgresql/data
networks:
  net:
volumes:
  docker:

