version: "3.2"
services:
  mayanedms:
    # replace username/repo:tag with your name and image details
    image: mayanedms/mayanedms:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:8083"
    environment:
      - MAYAN_DATABASE_ENGINE=django.db.backends.postgresql \
      - MAYAN_DATABASE_HOST=172.17.0.1 \
      - MAYAN_DATABASE_NAME=mayan \
      - MAYAN_DATABASE_PASSWORD=password \
      - MAYAN_DATABASE_USER=mayan \
      - MAYAN_DATABASE_CONN_MAX_AGE=60 \
    networks:
      - net
    volumes:
      - type: bind
        source: /mnt/docker/mayan-edms/media
        target: /var/lib/mayan
  mayanedms-postgres:
    # replace username/repo:tag with your name and image details
    image: postgres:9.5
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mayan
      - POSTGRES_DB=mayan
      - POSTGRES_PASSWORD=password
    networks:
      - net
    volumes:
      - type: bind
        source: /mnt/docker/mayan-edms/postgres
        target: /var/lib/postgresql/data
networks:
  net:
volumes:
  docker:
